name: Test And Release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Setup hub
      - uses: geertvdc/setup-hub@master      

      # Test
      - run: docker-compose up --build --abort-on-container-exit

      # Download jq
      - run: |
          curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 --output jq

      # create github release (docker hub will pick the new tag and will run the integration)
      - env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +%Y%m%d%H%M)
          export GIT_EDITOR=nano
          
          VERSIONS=$(jq -r '.dependencies | to_entries[] | join(" - ")' package.json)           

          hub release create 1.0.$DATE -m "Automatic release for the latest changes.

          Included FBL and FBL Plugins:

          $VERSIONS"